Subnet basic tests
filecoin-project/eudico pull request #158
Opened 2022-03-29 17:42 UTC by dnkolegov

This PR implements basic tests for subnets.

2022-03-30 07:04 UTC, adlrocha requested changes
I think we only need to clean a bit the code, and ideally adding support for `filcns` in root and we are ready for this first pass of itests.

2022-03-30 14:17 UTC, dnkolegov commented on api/api_hierarchical.go
> +	UnlockState(ctx context.Context, wallet address.Address, actor address.Address, subnet address.SubnetID,
fixed

2022-03-30 14:19 UTC, dnkolegov commented on chain/consensus/hierarchical/actors/sca/sca_cross.go
>  	"context"
fixed

2022-03-30 14:19 UTC, dnkolegov commented on chain/consensus/hierarchical/subnet/manager/crossmsg.go
> +	Type uint64
because then we will have to resolve dependency loop

2022-03-30 14:23 UTC, dnkolegov commented on chain/consensus/tendermint/message_cache.go
> +	cacheFinalityWait = 10000
you are right! fixed

2022-03-30 14:30 UTC, dnkolegov commented on chain/consensus/tendermint/mine.go
> +						log.Infof("successfully sent a message %s to Tendermint", id)
fixed

2022-03-30 14:30 UTC, dnkolegov commented on chain/consensus/tendermint/mine.go
> +						log.Error(err)
fixed

2022-03-30 14:30 UTC, dnkolegov commented on chain/consensus/tendermint/mine.go
> +				log.Infof("[subnet: %s, epoch: %d] >>>>> msg to send: %s", subnetID, base.Height()+1, id)
fixed

2022-03-30 14:30 UTC, dnkolegov commented on chain/consensus/tendermint/mine.go
> +			log.Infof("[subnet: %s, epoch: %d] retrieved %d msgs", subnetID, base.Height()+1, len(msgs))
fixed

2022-03-30 16:10 UTC, dnkolegov commented on chain/consensus/tendermint/mine.go
> +			crossMsgs, err := api.GetUnverifiedCrossMsgsPool(ctx, subnetID, base.Height()+1)
Yes, I believe that is still the case. You are totally right.

2022-03-30 16:19 UTC, dnkolegov commented on chain/consensus/tendermint/mine.go
> +			log.Infof("[subnet: %s, epoch: %d] try to sync a block", subnetID, base.Height()+1)
The same as above.

2022-03-30 16:22 UTC, dnkolegov commented on itests/eudico_subnet_test.go
> +	t.Logf(">>>>> wallet addr: %s", addr)
fixed

2022-03-30 16:28 UTC, dnkolegov commented on itests/eudico_subnet_test.go
> +	t.Log("\t>>>>> funding yourself")
done

2022-03-30 16:51 UTC, dnkolegov commented on itests/kit/miner_eudico.go
> +	for n < limit {
fixed via `getSubnetActor` and `getSubnetChainHead`, please review

2022-03-30 17:18 UTC, dnkolegov commented on itests/eudico_subnet_test.go
> +	params.Method = abi.MethodNum(uint64(builtin.MethodSend))
fixed

2022-03-31 07:40 UTC, adlrocha commented on chain/consensus/hierarchical/subnet/manager/crossmsg.go
> +	Type uint64
Understood.

2022-03-31 07:41 UTC, adlrocha commented on itests/kit/miner_eudico.go
> +	for n < limit {
Can you point me to the code? I don't seem to find it :(

2022-03-31 07:48 UTC, dnkolegov commented on itests/kit/miner_eudico.go
> +	for n < limit {
https://github.com/filecoin-project/eudico/blob/subnet-basic-tests/itests/kit/miner_eudico.go#L21

2022-03-31 07:50 UTC, adlrocha commented on itests/kit/miner_eudico.go
> +	for n < limit {
LGTM. Thanks!

2022-03-31 08:01 UTC, dnkolegov commented on chain/consensus/hierarchical/subnet/manager/crossmsg.go
> +	var (
fixed

2022-03-31 14:10 UTC, dnkolegov commented on itests/kit/ensemble_eudico.go
> +	case hierarchical.Tendermint:
Will be addressed here - https://github.com/filecoin-project/eudico/issues/160

2022-03-31 14:11 UTC, dnkolegov commented on itests/kit/ensemble_opts.go
> +func RootFilcns() EnsembleOpt {
Will be addressed here - https://github.com/filecoin-project/eudico/issues/160

2022-03-31 14:15 UTC, dnkolegov commented on itests/kit/ensemble_eudico.go
> +		var rootGenesisBytes []byte
Will be addressed in https://github.com/filecoin-project/eudico/issues/161

2022-03-31 14:28 UTC, adlrocha commented on itests/eudico_subnet_test.go
> +	var st sca.SCAState
Let's address this in the next round of itests.

2022-03-31 14:29 UTC, adlrocha commented on itests/kit/ensemble_eudico.go
> +	n.t.Log(">>>>> stop tendermint")
Same

2022-03-31 14:29 UTC, adlrocha approved these changes
LGTM! Feel free to merge.

2022-03-31 14:38 UTC, dnkolegov commented on itests/kit/ensemble_eudico.go
> +	n.t.Log(">>>>> stop tendermint")
fixed

2022-03-31 14:38 UTC, dnkolegov commented on itests/kit/ensemble_eudico.go
> +	n.t.Log(">>>>> tendermint container ID:", n.tendermintContainerID)
fixed

2022-03-31 14:38 UTC, dnkolegov commented on itests/kit/ensemble_eudico.go
> +	n.t.Log(">>>>> start tendermint")
fixed

2022-03-31 14:50 UTC, merged