WIP - feat:metric:Introduce subnet related metrics
filecoin-project/eudico pull request #226
Opened 2022-07-24 13:54 UTC by cryptoAtwill

## Related Issues

## Proposed Changes

- Adding `SubnetSpinUpDuration` and `SubnetCount` to the existing list of metrics
- Adding the measurements to the `addSubnet` command. 

## Additional Info

This PR is for early preview. Currently `lotus-stats` is giving some errors, need to find out why on that one first.

## Checklist

Before you mark the PR ready for review, please make sure that:
- [ ] All commits have a clear commit message.
- [ ] The PR title is in the form of of `<PR type>: <area>: <change being made>`
    - example: ` fix: mempool: Introduce a cache for valid signatures`
    - `PR type`: _fix_, _feat_, _INTERFACE BREAKING CHANGE_, _CONSENSUS BREAKING_, _build_, _chore_, _ci_, _docs_,_perf_, _refactor_, _revert_, _style_, _test_
    - `area`: _api_, _chain_, _state_, _vm_, _data transfer_, _market_, _mempool_, _message_, _block production_, _multisig_, _networking_, _paychan_, _proving_, _sealing_, _wallet_, _deps_
- [ ] This PR has tests for new functionality or change in behaviour
- [ ] If new user-facing features are introduced, clear usage guidelines and / or documentation updates should be included in https://lotus.filecoin.io or [Discussion Tutorials.](https://github.com/filecoin-project/lotus/discussions/categories/tutorials)
- [ ] CI is green

2022-07-25 07:04 UTC, adlrocha requested changes
I did a first pass. Ping if you need any additional reviews. Thanks!

2022-07-25 07:04 UTC, adlrocha commented on cmd/eudico/subnet.go
> +		sctx, _ := tag.New(ctx, tag.Upsert(metrics.SubnetType, cctx.String("consensus")))
This is not correct. To deploy a subnet, you first `subnet add` to deploy the subnet actor that will govern the subnet in the parent (no subnet is deployed in this step), and then when you `subnet join` is when all the stack for your subnet is initialized. Here you are only measuring the time to deploy the subnet actor.

Also, this is a sync command that waits for 5 epochs "finality" to be sure that the actor has been deployed successfully. I would suggest getting the metrics directly from the code at `chain/consensus/hierarchical`. It will allow you to get more fine-grained metrics (these commands abstract many of the low-level details of the protocol).

2022-07-25 07:04 UTC, adlrocha commented on cmd/lotus-stats/README.md
> +LOTUS_STATS_INFLUX_ADDR="http://192.168.1.94:8086"
Why this IP? Is this the specific one that you got in your environment? If this is the case is probably better to leave it as `localhost` or a placeholder like `<influx_ip>`.

2022-07-25 07:04 UTC, adlrocha commented on metrics/metrics.go
> +	SubnetCountView = &view.View{
If we add this metric, we should ensure that we count the active subnets (we increase it when we register a new subnet, and we decrease when we leave it). Actually, I think it'll be even more interesting to track the number of subnet in each state `Active`, `Inactive` and `killed`.

2022-07-25 07:04 UTC, adlrocha commented on .devcontainer/devcontainer.json
> +// https://github.com/microsoft/vscode-dev-containers/tree/v0.187.0/containers/go
What is this docker container? It'll be helpful to add a few notes on what is this, how it is used, etc.

2022-07-25 08:45 UTC, cryptoAtwill commented on cmd/eudico/subnet.go
> +		sctx, _ := tag.New(ctx, tag.Upsert(metrics.SubnetType, cctx.String("consensus")))
For add, do we measure the time here or actually in the join? We should measure the time when the msg gets back? Like at this point: https://github.com/filecoin-project/eudico/blob/110c4f2c8edceb2b8bb4489b4847c190a1dbf344/chain/consensus/hierarchical/subnet/submgr/manager.go#L532

2022-07-25 10:11 UTC, adlrocha commented on cmd/eudico/subnet.go
> +		sctx, _ := tag.New(ctx, tag.Upsert(metrics.SubnetType, cctx.String("consensus")))
As discussed in Slack, is really up to what you want to measure. Let's first gather a few sample metrics and then refine with different measurements of the end-to-end flow. Thanks!

2022-07-26 16:24 UTC, adlrocha commented
@cryptoAtwill, is this PR overwritten by #227? Should we close this one?

2022-07-27 06:23 UTC, closed without merging